#!/usr/bin/env bash
# Python format check script
# Generated by Scylla E2E test framework

set -euo pipefail

WORKSPACE="/home/mvillmow/fullruns/test001-dryrun/2026-01-20T06-13-07-test-001/T6/01/run_01/workspace"

cd "$WORKSPACE"
ruff check .
