#!/usr/bin/env bash
# Python syntax check script
# Generated by Scylla E2E test framework

set -euo pipefail

WORKSPACE="/home/mvillmow/fullruns/test001-dryrun/2026-01-20T06-13-07-test-001/T4/01/run_01/workspace"

cd "$WORKSPACE"
python -m compileall -q .
