#!/usr/bin/env python3
"""Validate that a commit message follows the Conventional Commits spec.

Used as a pre-commit `commit-msg` stage hook. The first non-comment, non-blank
line of the commit message must match:

    <type>(<optional scope>)<optional !>: <subject>

where <type> is one of the conventional types listed below. Merge commits
(`Merge ...`), revert commits (`Revert ...`), and fixup/squash commits
(generated by `git commit --fixup/--squash`) are accepted as-is.

Exit code: 0 if valid; 1 if invalid (with an explanation printed to stderr).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Conventional Commits spec (https://www.conventionalcommits.org/) plus the
# common extensions documented in CLAUDE.md.
ALLOWED_TYPES = (
    "feat",
    "fix",
    "docs",
    "style",
    "refactor",
    "perf",
    "test",
    "build",
    "ci",
    "chore",
    "revert",
)

PATTERN = re.compile(
    r"^(?P<type>" + "|".join(ALLOWED_TYPES) + r")"
    r"(?:\((?P<scope>[a-z0-9][a-z0-9 _,.\-/]*)\))?"
    r"(?P<bang>!)?"
    r":\s+(?P<subject>\S.*\S)$"
)

GIT_GENERATED_PREFIXES = ("Merge ", "Revert ", "fixup!", "squash!", "amend!")


def first_message_line(path: Path) -> str:
    """Return the first non-blank, non-comment line of the commit message."""
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        return raw
    return ""


def main(argv: list[str]) -> int:
    """Validate the commit message file passed by pre-commit."""
    if len(argv) != 2:
        print("usage: check_conventional_commit.py <commit-msg-file>", file=sys.stderr)
        return 2

    path = Path(argv[1])
    if not path.is_file():
        print(f"error: commit message file not found: {path}", file=sys.stderr)
        return 2

    subject = first_message_line(path)
    if not subject:
        print("error: commit message is empty", file=sys.stderr)
        return 1

    if subject.startswith(GIT_GENERATED_PREFIXES):
        return 0

    if PATTERN.match(subject):
        return 0

    print(
        "error: commit subject does not match Conventional Commits format.\n"
        f"  got:      {subject!r}\n"
        f"  expected: <type>(<scope>)<!>: <subject>\n"
        f"  types:    {', '.join(ALLOWED_TYPES)}\n"
        "  example:  fix(metrics): correct token counting logic\n"
        "See CLAUDE.md > 'Commit Message Format'.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
